name: Build and Deploy DITA HTML

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install DITA-OT
        run: |
          wget https://github.com/dita-ot/dita-ot/releases/download/4.2/dita-ot-4.2.zip
          unzip dita-ot-4.2.zip
          mv dita-ot-4.2 dita-ot

      - name: Download DITA Bootstrap plugin
        run: |
          wget https://github.com/jason-fox/dita-bootstrap/archive/refs/heads/develop.zip -O dita-bootstrap.zip
          unzip dita-bootstrap.zip
          mv dita-bootstrap-develop dita-bootstrap

      - name: Install Bootstrap plugin if not installed
        run: |
          if [ ! -d "./dita-ot/plugins/net.infotexture.dita-bootstrap" ]; then
            echo "Bootstrap plugin not found, downloading and installing..."
            wget https://github.com/jason-fox/dita-bootstrap/archive/refs/heads/develop.zip -O dita-bootstrap.zip
            unzip dita-bootstrap.zip
            mkdir dita-bootstrap-temp
            cp -r dita-bootstrap-develop/* dita-bootstrap-temp/
            ./dita-ot/bin/dita install ./dita-bootstrap-temp
          else
            echo "Bootstrap plugin already installed, skipping installation."
          fi

      - name: Build HTML5
        run: |
          ./dita-ot/bin/dita -i dataclean.ditamap -f html5-bootstrap -o out/html5

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out/html5
