name: Build and Deploy DITA HTML

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install DITA-OT
        run: |
          wget https://github.com/dita-ot/dita-ot/releases/download/4.2/dita-ot-4.2.zip
          unzip dita-ot-4.2.zip
          mv dita-ot-4.2 dita-ot

      - name: Install Bootstrap plugin
        run: ./dita-ot/bin/dita install net.infotexture.dita-bootstrap

      - name: Build HTML5
        run: |
          ./dita-ot/bin/dita -i dataclean.ditamap \
          -f html5-bootstrap \
          -o out/html5 \
          -Dargs.output.relative=true \
          -Dargs.bootstrap.theme.css.relative=true

      - name: Rename toc.html to index.html
        run: cp out/html5/toc.html out/html5/index.html

      - name: Update HTML to use CDN Bootstrap
        run: |
          for file in out/html5/*.html; do
            # Supprime les <link> et <script> vers common-*.css/js
            sed -i '/common.*\.css/d' "$file"
            sed -i '/css-theme-switcher/d' "$file"
            sed -i '/lunr-client/d' "$file"
            # Ajoute les liens CDN après <head>
            sed -i '/<head>/a \
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
            <link rel="stylesheet" type="text/css" href="css/commonltr.css">
            <link rel="stylesheet" type="text/css" href="./css/common-extended.css"><link rel="stylesheet" type="text/css" href="css/theme.css">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css" integrity="sha384-CK2SzKma4jA5H/MXDUU7i1TqZlCFaD4T01vtyDFvPlD97JQyS+IsSh1nI2EFbp" crossorigin="anonymous">
            done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out/html5
